### ISSUE TITLE
FULL TURBO cache hits (seems to) result in "no .next found" and build fails

### ISSUE THREAD

**Issue by joelhooks** [skillrecordings/turbo-playground#18]
This build fails and had a `FULL TURBO` hit: https://github.com/skillrecordings/turbo-playground/runs/3306279489?check_suite_focus=true

<img width="1104" alt="Screen Shot 2021-08-11 at 4 10 46 PM" src="https://user-images.githubusercontent.com/86834/129115219-4ebc0596-581b-4b66-a46b-17f8f04b7d6b.png">

```
skill-product-starter:start: ready - started server on 0.0.0.0:3004, url: http://localhost:3004
skill-product-starter:start:  ERROR  Command failed with exit code 1.
skill-product-starter:start: Error: Could not find a production build in the '/home/runner/work/turbo-playground/turbo-playground/apps/next-product-starter/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
skill-product-starter:start:     at Server.readBuildId (/home/runner/work/turbo-playground/turbo-playground/node_modules/.pnpm/next@11.1.0_f31b35bdaa3b7c2fce82404f09d2dac4/node_modules/next/dist/server/next-server.js:1559:23)
skill-product-starter:start:     at new Server (/home/runner/work/turbo-playground/turbo-playground/node_modules/.pnpm/next@11.1.0_f31b35bdaa3b7c2fce82404f09d2dac4/node_modules/next/dist/server/next-server.js:92:29)
skill-product-starter:start:     at NextServer.createServer (/home/runner/work/turbo-playground/turbo-playground/node_modules/.pnpm/next@11.1.0_f31b35bdaa3b7c2fce82404f09d2dac4/node_modules/next/dist/server/next.js:107:16)
skill-product-starter:start:     at async /home/runner/work/turbo-playground/turbo-playground/node_modules/.pnpm/next@11.1.0_f31b35bdaa3b7c2fce82404f09d2dac4/node_modules/next/dist/server/next.js:119:31
skill-product-starter:start: Error: command finished with error: exit status 1
 ERROR  Command failed with exit code 1.
(node:4016) UnhandledPromiseRejectionWarning: Error: The process '/home/runner/setup-pnpm/node_modules/.bin/pnpm' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/cypress-io/github-action/v2/dist/index.js:1135:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/cypress-io/github-action/v2/dist/index.js:1118:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/cypress-io/github-action/v2/dist/index.js:1012:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:4016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4016) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
http://localhost:3004 timed out on retry 121 of 5, elapsed 150254ms, limit 150000ms
Error: connect ECONNREFUSED 127.0.0.1:3004
```

@jaredpalmer This build passes wth the `--force` flag added to `turbo run build --force`

**Comment by joelhooks** [comment]
also fails on vercel in FULL TURBO situations

<img width="1335" alt="Screen Shot 2021-08-12 at 4 02 26 PM" src="https://user-images.githubusercontent.com/86834/129280886-9cec4351-6128-461d-b338-bfe51b077641.png">

**Comment by joelhooks** [comment]
adding these lines fixed this issue

https://github.com/skillrecordings/turbo-playground/blob/f5024a0f5f6f5ffd7e78b985f53843fe392e4285/package.json#L44-L53

Can't tell if it affects cache hits.
